apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: llm-runtime
  namespace: docs-agent
spec:
  supportedModelFormats:
    - name: huggingface
      version: "1"
      autoSelect: true
  containers:
    - name: kserve-container
      image: index.docker.io/kserve/huggingfaceserver:v0.17.0-gpu
      command: ["python", "-m", "huggingfaceserver"]
      resources:
        requests:
          cpu: "2"
          memory: "12Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "4"
          memory: "16Gi"
          nvidia.com/gpu: "1"
